[build]
  publish = "public"
  command = "npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "cheerio", "node-fetch", "@netlify/blobs", "serverless-http"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
